### ISSUE TITLE
helper.py needs small update to work with watson_developer_cloud version 1.0

### ISSUE THREAD

**Issue by mryoho** [udacity/AIND-NLP-Bookworm#2]
Change the environments line in the following to  `"environment": "list_environments"` in the following snippet. Alternatively, give some guidance on which version of the `watson_developer_cloud` to install. Reference the [repo](https://github.com/watson-developer-cloud/python-sdk/blob/254430e44a6dc3c73e69284188b31b7611258b75/watson_developer_cloud/discovery_v1.py) for the change.
```
# Methods for each object type
    list_methods = {
        "environment": "list_environments",
        "configuration": "list_configurations",
        "collection": "list_collections",
        "workspace": "list_workspaces"
    }
```

See this [forum post](https://discussions.udacity.com/t/ibm-bluemix-bookworm-project-attributeerror-discoveryv1-object-has-no-attribute-get-environments/452777/20) for more info.

**Comment by mryoho** [comment]
There's actually a lot of other stuff that has to be updated for the version 1 of the API, so perhaps it doesn't make sense to do this update just yet.

**Comment by subhashb** [comment]
Looks like fixating on the previous major release works fine. Install `watson-developer-cloud` with:
    
    pip install 'watson-developer-cloud==0.26.1'
