### ISSUE TITLE
The Watson Discovery Service no longer supports Alchemy Language enrichments

### ISSUE THREAD

**Issue by petermetz** [udacity/AIND-NLP-Bookworm#3]
When executing the notebook's first test I get the error below:

`WatsonException: Error: The Watson Discovery Service no longer supports Alchemy Language enrichments. Update your configuration to use Natural Language Understanding enrichments., Code: 400
`

https://www.ibm.com/blogs/bluemix/2017/03/bye-bye-alchemyapi/

**Comment by Rendiere** [comment]
@cgearhart Any update on this / idea on how to solve this issue?
Running into multiple issues when previewing a concentration for the AIND is quite frustrating and 100% defeats the purpose of the introduction. 

Please consider updating this project to a working version. 

For example, the `pip install watson-developer-cloud` command also needs to be updated to `pip install -I watson-developer-cloud==0.26.1`.
